language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - sudo apt-get install python-software-properties
  - sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
  - sudo add-apt-repository 'deb http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu precise main'
  - sudo apt-get update
  - sudo apt-get install mariadb-server mariadb-client
  - mysql -u root < 'CREATE DATABASE THR_CMS;'
  - php artistan migrate
  - php artistan db:seed

matrix:
    allow_failures:
        - php: 7.0

sudo: true

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit